version: '3.8'

services:
  gopher_db:
    image: "postgres:14-alpine"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gopher
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:  
    depends_on:
      - gopher_db
    build: .
    container_name: gopher_trade
    ports:
      - "3000:3000"

volumes:
  postgres: