version: '3.8'

services:
  gopher_db:
    image: "postgres:14-alpine"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gopher
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:  
    depends_on:
      - gopher_db
    build: .
    container_name: gopher_trade
    environment:
      - PORT=3000
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_HOST=gopher_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_HOST=gopher_cache
      - REDIS_PORT=6379
      - DECIMAL_PLACES=5
    ports:
      - "3000:3000"

  gopher_cache:
    image: "redis:7-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres: