// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package exchange

import (
	"context"
	"sync"

	"github.com/jpgsaraceni/gopher-trade/app/domain/entities"
	"github.com/jpgsaraceni/gopher-trade/app/domain/vos"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
// 	func TestSomethingThatUsesRepository(t *testing.T) {
//
// 		// make and configure a mocked Repository
// 		mockedRepository := &RepositoryMock{
// 			CreateExchangeFunc: func(ctx context.Context, exc entities.Exchange) error {
// 				panic("mock out the CreateExchange method")
// 			},
// 			GetExchangeByCurrenciesFunc: func(ctx context.Context, from vos.CurrencyCode, to vos.CurrencyCode) (entities.Exchange, error) {
// 				panic("mock out the GetExchangeByCurrencies method")
// 			},
// 		}
//
// 		// use mockedRepository in code that requires Repository
// 		// and then make assertions.
//
// 	}
type RepositoryMock struct {
	// CreateExchangeFunc mocks the CreateExchange method.
	CreateExchangeFunc func(ctx context.Context, exc entities.Exchange) error

	// GetExchangeByCurrenciesFunc mocks the GetExchangeByCurrencies method.
	GetExchangeByCurrenciesFunc func(ctx context.Context, from vos.CurrencyCode, to vos.CurrencyCode) (entities.Exchange, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateExchange holds details about calls to the CreateExchange method.
		CreateExchange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exc is the exc argument value.
			Exc entities.Exchange
		}
		// GetExchangeByCurrencies holds details about calls to the GetExchangeByCurrencies method.
		GetExchangeByCurrencies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// From is the from argument value.
			From vos.CurrencyCode
			// To is the to argument value.
			To vos.CurrencyCode
		}
	}
	lockCreateExchange          sync.RWMutex
	lockGetExchangeByCurrencies sync.RWMutex
}

// CreateExchange calls CreateExchangeFunc.
func (mock *RepositoryMock) CreateExchange(ctx context.Context, exc entities.Exchange) error {
	if mock.CreateExchangeFunc == nil {
		panic("RepositoryMock.CreateExchangeFunc: method is nil but Repository.CreateExchange was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Exc entities.Exchange
	}{
		Ctx: ctx,
		Exc: exc,
	}
	mock.lockCreateExchange.Lock()
	mock.calls.CreateExchange = append(mock.calls.CreateExchange, callInfo)
	mock.lockCreateExchange.Unlock()
	return mock.CreateExchangeFunc(ctx, exc)
}

// CreateExchangeCalls gets all the calls that were made to CreateExchange.
// Check the length with:
//     len(mockedRepository.CreateExchangeCalls())
func (mock *RepositoryMock) CreateExchangeCalls() []struct {
	Ctx context.Context
	Exc entities.Exchange
} {
	var calls []struct {
		Ctx context.Context
		Exc entities.Exchange
	}
	mock.lockCreateExchange.RLock()
	calls = mock.calls.CreateExchange
	mock.lockCreateExchange.RUnlock()
	return calls
}

// GetExchangeByCurrencies calls GetExchangeByCurrenciesFunc.
func (mock *RepositoryMock) GetExchangeByCurrencies(ctx context.Context, from vos.CurrencyCode, to vos.CurrencyCode) (entities.Exchange, error) {
	if mock.GetExchangeByCurrenciesFunc == nil {
		panic("RepositoryMock.GetExchangeByCurrenciesFunc: method is nil but Repository.GetExchangeByCurrencies was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		From vos.CurrencyCode
		To   vos.CurrencyCode
	}{
		Ctx:  ctx,
		From: from,
		To:   to,
	}
	mock.lockGetExchangeByCurrencies.Lock()
	mock.calls.GetExchangeByCurrencies = append(mock.calls.GetExchangeByCurrencies, callInfo)
	mock.lockGetExchangeByCurrencies.Unlock()
	return mock.GetExchangeByCurrenciesFunc(ctx, from, to)
}

// GetExchangeByCurrenciesCalls gets all the calls that were made to GetExchangeByCurrencies.
// Check the length with:
//     len(mockedRepository.GetExchangeByCurrenciesCalls())
func (mock *RepositoryMock) GetExchangeByCurrenciesCalls() []struct {
	Ctx  context.Context
	From vos.CurrencyCode
	To   vos.CurrencyCode
} {
	var calls []struct {
		Ctx  context.Context
		From vos.CurrencyCode
		To   vos.CurrencyCode
	}
	mock.lockGetExchangeByCurrencies.RLock()
	calls = mock.calls.GetExchangeByCurrencies
	mock.lockGetExchangeByCurrencies.RUnlock()
	return calls
}
