definitions:
  currencies.CreateCurrencyRequest:
    properties:
      code:
        example: FAKEMONEY
        type: string
      usd_rate:
        example: "200.132"
        type: string
    type: object
  currencies.CreateCurrencyResponse:
    properties:
      code:
        example: USD
        type: string
      created_at:
        type: string
      id:
        example: 2171f348-54b4-4a1e-8643-0972a3daf400
        type: string
      updated_at:
        type: string
      usd_rate:
        example: "2.132"
        type: string
    type: object
  currencies.GetConversionResponse:
    properties:
      converted_amount:
        example: "23.431"
        type: string
    type: object
  responses.ErrorPayload:
    properties:
      error:
        example: Message for some error
        type: string
    type: object
info:
  contact:
    email: jpgome@id.uff.br
    name: João Saraceni
    url: https://www.linkedin.com/in/joaosaraceni/
  description: Gopher Trade is an api to get monetary exchange values.
  license:
    name: MIT
    url: https://github.com/jpgsaraceni/gopher-trade/blob/main/LICENSE
  title: Gopher Trade API
  version: 0.1.0
paths:
  /currencies:
    post:
      consumes:
      - application/json
      description: Creates an exchange rate from a specified currency to USD.
      parameters:
      - description: Currency Info
        in: body
        name: currency
        required: true
        schema:
          $ref: '#/definitions/currencies.CreateCurrencyRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/currencies.CreateCurrencyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorPayload'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responses.ErrorPayload'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorPayload'
      summary: Create a new currency exchange rate
      tags:
      - Currency
  /currencies/conversion:
    get:
      consumes:
      - application/json
      parameters:
      - description: From currency code
        in: query
        name: from
        required: true
        type: string
      - description: To currency code
        in: query
        name: to
        required: true
        type: string
      - description: Amount to be converted
        in: query
        name: amount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/currencies.GetConversionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorPayload'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorPayload'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorPayload'
      summary: Get a conversion for an existent rate
      tags:
      - Exchange
swagger: "2.0"
