name: Pull Request CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.github/workflows/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3.2.0
        - uses: actions/setup-go@v3.3.1
          with:
            go-version: 1.18
        - uses: actions/cache@v3.0.11
          with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
    
        - name: test
          run: go test -v ./...

        - name: build
          run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.18
          check-latest: false
      - uses: actions/cache@v3.0.11
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make lint
  
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.18
      - run: |
          make generate
          git diff --exit-code --ignore-space-change


